title: Valimisliit KODU
author:
email: kalle@neti.ee
description: 

twitter_username: jekyllrb
github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Inimesed
inimesed:
  - kood: 158
    nimi: Lemmi Oro
    amet: Rahandusministeerium, osakonnajuhataja
  - kood: 159
    nimi: Mall Petersen
    amet: Saku Tervisekeskus, perearst
  - kood: 160
    nimi: Argo Zirk
    amet: Saku Sporting, jalgpallitreener
  - kood: 161
    nimi: Merike Sisask
    amet: Tallinna Ülikool, sotsiaaltervishoiu professor
  - kood: 162
    nimi: Kairi Zaletajev
    amet: Saku Gümnaasium, õpetaja ja logopeed
  - kood: 163
    nimi: Tiina Ruut
    amet: Saku Tervisekeskus, pereõde
  - kood: 164
    nimi: Sirje Peterson
    amet: Saku Tervisekeskus, perearst
  - kood: 165
    nimi: Lembit Makstin
    amet: teedeinsener, ettevõtja
  - kood: 166
    nimi: Hanna-Lisa Kuslap
    amet: üliõpilane, Saku Sportingu treener
  - kood: 167
    nimi: Leila Talk
    amet: Saku kosmeetikatuba, kosmeetik
  - kood: 168
    nimi: Eili Erg
    amet: W-Glass OÜ, konsultant
  - kood: 169
    nimi: Külli Männik
    amet: Saku Tervisekeskus, jalahooldusspetsialist
  - kood: 170
    nimi: Marten Liiva
    amet: Forus Haldus OÜ, heakorraosakonna juht
  - kood: 171
    nimi: Maili Jorro
    amet: kinnisvarahalduse asjatundja
  - kood: 172
    nimi: Anna Lutter
    amet: Kurtna Kooli õpetaja, elustiiliettevõtja
  - kood: 173
    nimi: Kalle Pungas
    amet: Saue Vallavalitsus, abivallavanem
